export enum Icons {
  Search = "Search",
  Home = "Home",
  Chart = "Chart",
  User = "User",
  Notes = "Notes",
  Menu = "Menu",
  UserPin = "UserPin",
  Flag = "Flag",
  Mail = "Mail",
  Connect = "Connect",
  Minus = "Minus",
  Close = "Close",
  Arrow = "Arrow",
  Chevron = "Chevron",
  CheckboxOutline = "CheckboxOutline",
  CheckboxChecked = "CheckboxChecked",
  Phone = "Phone",
  Txt = "Txt",
  Skip = "Skip",
  Lock = "Lock",
}
